# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user_id', models.CharField(max_length=36, verbose_name='user id')),
                ('conditions', models.CharField(max_length=256, verbose_name='conditions')),
                ('export_data', models.FileField(upload_to='export/data/', verbose_name='export data')),
                ('export_file', models.FileField(upload_to='export/files/', verbose_name='export file')),
                ('export_format', models.CharField(default='json', max_length=8, verbose_name='export format')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='new', max_length=16, verbose_name='export status')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'model export',
                'verbose_name_plural': 'model export',
            },
        ),
    ]
