# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 10:32
from __future__ import unicode_literals

from django.db import migrations

from common.helpers.postgresql.extensions import LoadExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        LoadExtension('ltree')
    ]
