# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 11:21
from __future__ import unicode_literals

import common.helpers.postgresql.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='created at')),
                ('user_id', models.CharField(max_length=36, verbose_name='user id')),
                ('object_type', models.CharField(max_length=64, verbose_name='object type')),
                ('object_id', models.CharField(max_length=36, verbose_name='object id')),
                ('comment', models.TextField(verbose_name='comment')),
                ('path', common.helpers.postgresql.fields.LTreeField(verbose_name='comment path')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.Comment')),
            ],
            options={
                'ordering': ['parent_id', 'created_at'],
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
